// PureWipe — Generated by WFO project-scaffolding skill
// Stack : .NET net9.0 · Razor Pages · Bootstrap 5 · Decap CMS · JSON Content Layer
// Source: blueprints/code/Program.cs.template
//
// ── Substitution markers applied ─────────────────────────────────────────────
//   {{PROJECT_NAME}}    → PureWipe
//   {{DOTNET_VERSION}}  → net9.0
//
// ── Feature markers ──────────────────────────────────────────────────────────
//   [FEATURE: contact-form-handler]   Uncomment when contact-form-handler skill executes
//   [FEATURE: decap-custom-oauth]     Uncomment only when GitHub OAuth server-side is required
//
// Do not remove commented blocks — @Builder uses them as activation points.
// ─────────────────────────────────────────────────────────────────────────────

using PureWipe.Services;
using PureWipe.Models;

var builder = WebApplication.CreateBuilder(args);

// ── Razor Pages ───────────────────────────────────────────────────────────────
builder.Services.AddRazorPages();

// ── JSON Content Service (no EF, no DB — Git-backed content layer) ───────────
// Reads from: wwwroot/content/**/*.json
// Required:   every WFO project — never remove.
builder.Services.AddSingleton<IContentService, JsonContentService>();

// ── SEO options (marketing-seo-pack — always required) ───────────────────────
builder.Services.Configure<SeoOptions>(
    builder.Configuration.GetSection("Seo"));

// ── [FEATURE: contact-form-handler] ──────────────────────────────────────────
// Activate: when contact-form-handler skill has been executed.
// Requires: "Smtp" section in appsettings.json (never hard-code credentials).
//
// builder.Services.AddScoped<IContactFormService, ContactFormService>();
// builder.Services.AddScoped<IDistributorFormService, DistributorFormService>();
// builder.Services.Configure<SmtpOptions>(
//     builder.Configuration.GetSection("Smtp"));

// ── [FEATURE: decap-custom-oauth] ────────────────────────────────────────────
// Activate: ONLY when the project needs a custom GitHub OAuth server for Decap CMS.
// Default:  Decap CMS uses its own GitHub OAuth — no server-side code needed.
// Note:     base_url = origin only (e.g. https://example.com).
//           auth_endpoint = subpath (e.g. "site/auth").
//
// builder.Services.AddSingleton<IDecapAuthService, DecapAuthService>();
// builder.Services.Configure<DecapAuthOptions>(
//     builder.Configuration.GetSection("GitHub"));

// ─────────────────────────────────────────────────────────────────────────────
var app = builder.Build();

// ── Middleware ────────────────────────────────────────────────────────────────
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();

app.MapRazorPages();

// ── [FEATURE: decap-custom-oauth] — OAuth callback routing ───────────────────
// Activate: when IDecapAuthService is registered above.
// The subpath must match backend.auth_endpoint in wwwroot/admin/config.yml.
//
// app.MapGroup("/site").MapDecapAuthEndpoints();

app.Run();
