// PureWide3 — Generated by WFO project-scaffolding skill
// Stack : .NET net9.0 · Razor Pages · Bootstrap 5 · Decap CMS · JSON Content Layer
// Source: blueprints/code/Program.cs.template

using PureWide3.Services;
using PureWide3.Models;

var builder = WebApplication.CreateBuilder(args);

// ── Razor Pages ───────────────────────────────────────────────────────────────
builder.Services.AddRazorPages();

// ── Memory cache (used by ContentService) ─────────────────────────────────────
builder.Services.AddMemoryCache();

// ── JSON Content Service (no EF, no DB — Git-backed content layer) ───────────
// Reads from: wwwroot/content/**/*.json and wwwroot/content/blog/*.md
builder.Services.AddSingleton<IContentService, JsonContentService>();

// ── SEO options (marketing-seo-pack — always required) ───────────────────────
builder.Services.Configure<SeoOptions>(
    builder.Configuration.GetSection("Seo"));

// ── [FEATURE: contact-form-handler] ──────────────────────────────────────────
// Activate: when contact-form-handler skill has been executed.
// builder.Services.AddScoped<IContactFormService, ContactFormService>();
// builder.Services.Configure<SmtpOptions>(builder.Configuration.GetSection("Smtp"));

// ─────────────────────────────────────────────────────────────────────────────
var app = builder.Build();

// ── Middleware ────────────────────────────────────────────────────────────────
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

// Support PATH_BASE for shared-domain VPS topology (e.g. /purewide3)
var pathBase = Environment.GetEnvironmentVariable("PATH_BASE");
if (!string.IsNullOrEmpty(pathBase))
    app.UsePathBase(pathBase);

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();

app.MapRazorPages();

app.Run();
