// MiMascota.Models — BlogPost
// Maps to: wwwroot/content/blog/{slug}.md (YAML frontmatter + Markdown body)
// Generated by WFO project-scaffolding skill

namespace MiMascota.Models;

public class BlogPost
{
    public string Slug { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public DateTime Date { get; set; }
    public string FeaturedImage { get; set; } = string.Empty;
    public string Excerpt { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string? RelatedProduct { get; set; }
    public string BodyHtml { get; set; } = string.Empty;
}
