// MiMascota.Models — BrandAbout
// Maps to: wwwroot/content/about.json
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class BrandAbout
{
    [JsonPropertyName("brand_story")]
    public string BrandStory { get; set; } = string.Empty;

    [JsonPropertyName("mission")]
    public string Mission { get; set; } = string.Empty;

    [JsonPropertyName("vision")]
    public string Vision { get; set; } = string.Empty;

    [JsonPropertyName("values")]
    public List<string> Values { get; set; } = new();

    [JsonPropertyName("eco_commitment")]
    public string EcoCommitment { get; set; } = string.Empty;

    [JsonPropertyName("team")]
    public List<TeamMember>? Team { get; set; }
}

public class TeamMember
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    [JsonPropertyName("photo")]
    public string? Photo { get; set; }
}
