// MiMascota.Models — ContactConfig
// Maps to: wwwroot/content/contact.json
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class ContactConfig
{
    [JsonPropertyName("whatsapp_number")]
    public string WhatsappNumber { get; set; } = string.Empty;

    [JsonPropertyName("whatsapp_message")]
    public string WhatsappMessage { get; set; } = string.Empty;

    [JsonPropertyName("social_links")]
    public SocialLinks? SocialLinks { get; set; }

    [JsonPropertyName("distributors")]
    public List<Distributor>? Distributors { get; set; }

    /// <summary>Returns a pre-encoded wa.me URL for use in href attributes.</summary>
    public string WhatsappUrl =>
        $"https://wa.me/{WhatsappNumber.TrimStart('+').Replace(" ", string.Empty)}" +
        (string.IsNullOrWhiteSpace(WhatsappMessage)
            ? string.Empty
            : $"?text={Uri.EscapeDataString(WhatsappMessage)}");
}

public class SocialLinks
{
    [JsonPropertyName("instagram")]
    public string? Instagram { get; set; }

    [JsonPropertyName("facebook")]
    public string? Facebook { get; set; }

    [JsonPropertyName("tiktok")]
    public string? TikTok { get; set; }
}

public class Distributor
{
    [JsonPropertyName("city")]
    public string City { get; set; } = string.Empty;

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("address")]
    public string? Address { get; set; }

    [JsonPropertyName("phone")]
    public string? Phone { get; set; }
}
