// MiMascota.Models — GalleryItem
// Maps to: wwwroot/content/gallery.json → .items[]
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class GalleryRoot
{
    [JsonPropertyName("items")]
    public List<GalleryItem> Items { get; set; } = new();
}

public class GalleryItem
{
    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    [JsonPropertyName("caption")]
    public string? Caption { get; set; }

    [JsonPropertyName("line")]
    public string? Line { get; set; }

    [JsonPropertyName("type")]
    public string Type { get; set; } = "photo";
}
