// MiMascota.Models — HeroBanner
// Maps to: wwwroot/content/hero.json
// Decap collection: hero (singleton)
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class HeroBanner
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("cta_primary_text")]
    public string CtaPrimaryText { get; set; } = string.Empty;

    [JsonPropertyName("cta_primary_url")]
    public string CtaPrimaryUrl { get; set; } = string.Empty;

    [JsonPropertyName("cta_secondary_text")]
    public string? CtaSecondaryText { get; set; }

    [JsonPropertyName("cta_secondary_url")]
    public string? CtaSecondaryUrl { get; set; }

    [JsonPropertyName("background_image")]
    public string BackgroundImage { get; set; } = string.Empty;
}
