// MiMascota.Models — LegalContent
// Maps to: wwwroot/content/legal.json
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class LegalContent
{
    [JsonPropertyName("terms")]
    public string Terms { get; set; } = string.Empty;

    [JsonPropertyName("privacy")]
    public string Privacy { get; set; } = string.Empty;

    [JsonPropertyName("returns")]
    public string Returns { get; set; } = string.Empty;

    [JsonPropertyName("fiscal_info")]
    public string? FiscalInfo { get; set; }
}
