// MiMascota.Models — Product
// Maps to: wwwroot/content/products/{slug}.json
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class Product
{
    [JsonPropertyName("slug")]
    public string Slug { get; set; } = string.Empty;

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("line")]
    public string Line { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("ingredients")]
    public List<string> Ingredients { get; set; } = new();

    [JsonPropertyName("certifications")]
    public List<string>? Certifications { get; set; }

    [JsonPropertyName("usage_instructions")]
    public string UsageInstructions { get; set; } = string.Empty;

    [JsonPropertyName("warnings")]
    public string? Warnings { get; set; }

    [JsonPropertyName("presentations")]
    public List<string> Presentations { get; set; } = new();

    [JsonPropertyName("gallery_images")]
    public List<string> GalleryImages { get; set; } = new();

    [JsonPropertyName("related_products")]
    public List<string>? RelatedProducts { get; set; }

    [JsonPropertyName("cta_text")]
    public string? CtaText { get; set; }

    [JsonPropertyName("cta_url")]
    public string? CtaUrl { get; set; }
}
