// MiMascota.Models — ProductLine
// Maps to: wwwroot/content/product-lines.json → .lines[]
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class ProductLinesRoot
{
    [JsonPropertyName("lines")]
    public List<ProductLine> Lines { get; set; } = new();
}

public class ProductLine
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    [JsonPropertyName("cta_url")]
    public string CtaUrl { get; set; } = string.Empty;

    [JsonPropertyName("color_accent")]
    public string? ColorAccent { get; set; }
}
