// MiMascota.Models — SeoMeta
// Used by all PageModels to populate <head> meta tags and schema.org JSON-LD
// Generated by WFO project-scaffolding skill

namespace MiMascota.Models;

public class SeoMeta
{
    public string Title { get; set; } = "Mi Mascota — Higiene segura para tu mascota";
    public string Description { get; set; } = "Toallitas biodegradables con ingredientes 100% seguros para perros y gatos.";
    public string? CanonicalUrl { get; set; }
    public string? OgImage { get; set; }
    public string OgType { get; set; } = "website";
    public string? SchemaJson { get; set; }
}
