// MiMascota.Models — Testimonial
// Maps to: wwwroot/content/testimonials.json → .items[]
// Generated by WFO project-scaffolding skill

using System.Text.Json.Serialization;

namespace MiMascota.Models;

public class TestimonialsRoot
{
    [JsonPropertyName("items")]
    public List<Testimonial> Items { get; set; } = new();
}

public class Testimonial
{
    [JsonPropertyName("author")]
    public string Author { get; set; } = string.Empty;

    [JsonPropertyName("rating")]
    public int Rating { get; set; }

    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;

    [JsonPropertyName("line")]
    public string? Line { get; set; }
}
