#!/usr/bin/env bash
# push-scaffold-nexoescolar.sh
# Pushes the NexoEscolar .NET 9 scaffold to the client repo.
# Usage: GITHUB_TOKEN=<token> bash scripts/push-scaffold-nexoescolar.sh
# ── WFO Repository Boundary: client repo contains project code ONLY ──────────

set -euo pipefail

SCAFFOLD_DIR="$(cd "$(dirname "$0")/../scaffold-output/nexoescolar-web" && pwd)"
CLIENT_REPO_URL="https://github.com/carlosperez1986/nexoescolar.git"
BRANCH="main"
TMP_DIR="/tmp/nexoescolar-push-$(date +%s)"

if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "ERROR: GITHUB_TOKEN is not set. Export it before running this script."
  exit 1
fi

echo "▶ Cloning client repo into $TMP_DIR ..."
git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/carlosperez1986/nexoescolar.git" "$TMP_DIR"

echo "▶ Copying scaffold (excluding WFO orchestration files) ..."
rsync -av --exclude=".git" "$SCAFFOLD_DIR/" "$TMP_DIR/"

cd "$TMP_DIR"

echo "▶ Committing scaffold ..."
git config user.email "wfo-bot@nexoescolar.com"
git config user.name  "WFO Orchestrator"
git add -A
git commit -m "feat: WFO project-scaffolding — .NET 9 / Bootstrap 5 / Decap CMS scaffold

Stack: .NET 9 Razor Pages · Bootstrap 5 · AOS.js · Bootstrap Icons · Decap CMS
Generated by WFO project-scaffolding skill · 2026-05-02
Sections: Hero, Problema, Funciones (Bento), Beneficios Hub, App, Trust, Demo Form, FAQ, Footer
Build: dotnet build → 0 errors 0 warnings (verified)"

echo "▶ Pushing to $CLIENT_REPO_URL branch $BRANCH ..."
git push origin "$BRANCH"

echo ""
echo "✅ NexoEscolar scaffold pushed to $CLIENT_REPO_URL"
echo "   Next step: GitHub Actions build.yml will run automatically."
rm -rf "$TMP_DIR"
