#!/usr/bin/env bash
# push-scaffold-mimascota.sh
# Pushes the pre-generated scaffold from scaffold-output/mimascota-web/ to the
# client repository carlosperez1986/mimascota-web.
#
# Prerequisites:
#   - gh CLI authenticated with repo scope
#   - git configured (name + email)
#
# Usage:
#   bash scripts/push-scaffold-mimascota.sh

set -euo pipefail

REPO="carlosperez1986/mimascota-web"
SCAFFOLD_DIR="$(dirname "$0")/../scaffold-output/mimascota-web"
BRANCH="main"
TEMP_DIR="$(mktemp -d)"

echo "==> Checking gh authentication..."
gh auth status || { echo "ERROR: gh CLI not authenticated. Run: gh auth login"; exit 1; }

echo "==> Checking if repo ${REPO} exists..."
if gh repo view "${REPO}" &>/dev/null; then
    echo "    Repo exists — cloning..."
    gh repo clone "${REPO}" "${TEMP_DIR}/mimascota-web"
    cd "${TEMP_DIR}/mimascota-web"
else
    echo "ERROR: Repo ${REPO} does not exist."
    echo "       Run the github-project-bootstrap script first:"
    echo "         bash scripts/bootstrap-github-mimascota.sh"
    exit 1
fi

echo "==> Copying scaffold files..."
rsync -av --exclude='.git' \
    "${SCAFFOLD_DIR}/" \
    "${TEMP_DIR}/mimascota-web/"

echo "==> Staging all files..."
git add -A

if git diff --cached --quiet; then
    echo "    Nothing to commit — scaffold already up to date."
    exit 0
fi

echo "==> Committing..."
git commit -m "feat: initial scaffold from WFO project-scaffolding skill

Generated by WFO Orchestrator.
Stack: .NET 9 · Razor Pages · Bootstrap 5 · Decap CMS · Git-backed JSON/MD
Skill: project-scaffolding
Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "==> Pushing to ${REPO} (${BRANCH})..."
git push origin "${BRANCH}"

echo ""
echo "✅ Scaffold pushed to https://github.com/${REPO}"
echo "   Next step: set GitHub Actions secrets + run vps-provisioning skill"
echo ""
echo "   Required secrets in carlosperez1986/mimascota-web:"
echo "     PASSWORD                     → SSH password to VPS"
echo "     DECAP_GITHUB_CLIENT_ID       → GitHub OAuth App Client ID"
echo "     DECAP_GITHUB_CLIENT_SECRET   → GitHub OAuth App Client Secret"
echo ""
echo "   Required variables:"
echo "     SERVER_IP                    → VPS IP or hostname"
echo "     USERNAME                     → SSH user"
